export const Category = [
  {
    title: 'Egg Cakes',
  },
  {
    title: 'EggLess Cakes',
  },
  {
    title: 'Icecream Cakes',
  },
  {
    title: 'Cup Cakes',
  },
];

export const Flavours = [
  {
    title: 'Chocolate',
  },
  {
    title: 'Butterscotch',
  },
  {
    title: 'Strawberry',
  },
  {
    title: 'Caramel',
  },
  {
    title: 'Vanilla',
  },
];

export const Shape = [
  {
    title: 'Heart',
  },
  {
    title: 'Round',
  },
  {
    title: 'Rectangle',
  },
];

export const BestSeller = [
  {
    name: 'chocotruffle',
    image: '',
    rating: 4.8,
    amount: '480',
    quantity: '500gms',
    offer: '10% off',
  },
  {
    name: 'crunchy butterscotch',
    image: '',
    rating: 4.2,
    amount: '530',
    quantity: '500gms',
    offer: '20% off',
  },
  {
    name: 'strawberry delight',
    image: '',
    rating: 4.3,
    amount: '550',
    quantity: '500gms',
    offer: '15% off',
  },
  {
    name: 'caramel delight',
    image: '',
    rating: 3.8,
    amount: '420',
    quantity: '500gms',
    offer: '15% off',
  },
  {
    name: 'Snickerdoodles',
    image: '',
    rating: 3.5,
    amount: '480',
    quantity: '500gms',
    offer: '8% off',
  },
  {
    name: 'Homemade bread',
    image: '',
    rating: 4.7,
    amount: '450',
    quantity: '500gms',
    offer: '20% off',
  },
  {
    name: 'Chocolate Chip Cookies',
    image: '',
    rating: 4.5,
    amount: '350',
    quantity: '500gms',
    offer: '10% off',
  },
  {
    name: 'Heavenly Butterscotch',
    image: '',
    rating: 4.1,
    amount: '550',
    quantity: '500gms',
    offer: '20% off',
  },
  {
    name: 'Shortbread Cookies',
    image: '',
    rating: 4.3,
    amount: '460',
    quantity: '250gms',
    offer: '15% off',
  },
  {
    name: 'Chocolate walnut',
    image: '',
    rating: 3.5,
    amount: '520',
    quantity: '1kg',
    offer: '20% off',
  },
];

export const items = [
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'chocotruffle',
    image: '',
    rating: 4.8,
    amount: '430',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'chocotruffle',
    image: '',
    rating: 4.9,
    amount: '430',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'chocotruffle',
    image: '',
    rating: 4.8,
    amount: '430',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'chocotruffle',
    image: '',
    rating: 4.9,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'chocotruffle',
    image: '',
    rating: 4.9,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'chocotruffle',
    image: '',
    rating: 4.9,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Darkchocolate',
    image: '',
    rating: 4.7,
    amount: '420',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Darkchocolate',
    image: '',
    rating: 4.7,
    amount: '420',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Darkchocolate',
    image: '',
    rating: 4.7,
    amount: '420',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Darkchocolate',
    image: '',
    rating: 4.6,
    amount: '470',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Darkchocolate',
    image: '',
    rating: 4.6,
    amount: '470',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Darkchocolate',
    image: '',
    rating: 4.6,
    amount: '470',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Black Forest',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '490',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '490',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Lava Cake',
    image: '',
    rating: 4.8,
    amount: '490',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    id: 28,
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '690',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '690',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Raspberry Cake',
    image: '',
    rating: 4.8,
    amount: '690',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '575',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '575',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '575',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 1,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '625',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 2,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '625',
    quantity: '500g',
    offer: '20% off',
  },
  {
    id: 36,
    category_Id: 2,
    flavour_Id: 1,
    shape_Id: 3,
    name: 'Chocolate Fudge',
    image: '',
    rating: 4.8,
    amount: '625',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '549',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '549',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '549',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '599',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '599',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Delight',
    image: '',
    rating: 4.9,
    amount: '599',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '250',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '250',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '250',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '300',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '300',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Premium',
    image: '',
    rating: 4.8,
    amount: '300',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '450',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Bourbon Cake',
    image: '',
    rating: 4.8,
    amount: '500',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '570',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '570',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '570',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '620',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '620',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Hazelnut Cake',
    image: '',
    rating: 4.8,
    amount: '620',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '589',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '589',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '589',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '630',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '630',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Caramel Cake',
    image: '',
    rating: 4.8,
    amount: '630',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '750',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '750',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '750',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 1,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '799',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 2,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '799',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 2,
    shape_Id: 3,
    name: 'Butterscotch Blueberry Cake',
    image: '',
    rating: 4.8,
    amount: '799',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '370',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '370',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '370',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '420',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Coconut',
    image: '',
    rating: 4.7,
    amount: '420',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '495',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '495',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '495',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '535',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '535',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Almond Cake',
    image: '',
    rating: 4.7,
    amount: '535',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '600',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '600',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '600',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Basil Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '780',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '780',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '780',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '830',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '830',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '830',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 1,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '870',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 2,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '870',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 3,
    shape_Id: 3,
    name: 'Strawberry Shortcake',
    image: '',
    rating: 4.7,
    amount: '870',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '800',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '840',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '840',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Basic Red Velvet Cake',
    image: '',
    rating: 4.7,
    amount: '840',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '200',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '200',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '200',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '230',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '230',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Jar Cake',
    image: '',
    rating: 4.7,
    amount: '230',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '735',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '735',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '735',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '785',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '785',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Cheese Cake',
    image: '',
    rating: 4.7,
    amount: '785',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '900',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '900',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '900',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '970',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '970',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Peanut Butter Cake',
    image: '',
    rating: 4.7,
    amount: '970',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '675',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '675',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '675',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '725',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '725',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet White Chocolate Cake',
    image: '',
    rating: 4.7,
    amount: '725',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '715',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '715',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '715',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 1,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '755',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 2,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '755',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 4,
    shape_Id: 3,
    name: 'Red Velvet Tiramisu Cake',
    image: '',
    rating: 4.7,
    amount: '755',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '399',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '399',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '399',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '445',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '445',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Vanilla Pineapple Cake',
    image: '',
    rating: 4.7,
    amount: '445',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Blueberry Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },

  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '480',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Raspberry Bean Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '630',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '630',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Caramel Cake',
    image: '',
    rating: 4.7,
    amount: '650',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '670',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '670',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '670',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Lavender Cake',
    image: '',
    rating: 4.7,
    amount: '720',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 1,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '530',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 1,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 2,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
  {
    category_Id: 2,
    flavour_Id: 5,
    shape_Id: 3,
    name: 'Coconut Cake',
    image: '',
    rating: 4.7,
    amount: '580',
    quantity: '500g',
    offer: '20% off',
  },
];
